# Generated by Django 5.2.4 on 2025-08-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcatalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookGenre',
        ),
    ]
